### ISSUE TITLE
Undefined symbol "utimensat"

### ISSUE THREAD

**Issue by scorpio1441** [bapt/indexinfo#8]
I'm getting `Undefined symbol "utimensat"` error when trying to upgrade to version 0.2.6.

> root@host:/usr/home/alex # pkg upgrade indexinfo
> Updating FreeBSD repository catalogue...
> FreeBSD repository is up-to-date.
> All repositories are up-to-date.
> Checking integrity... done (0 conflicting)
> The following 1 package(s) will be affected (of 0 checked):
> 
> Installed packages to be UPGRADED:
>         indexinfo: 0.2.5 -> 0.2.6
> 
> Number of packages to be upgraded: 1
> 
> Proceed with this action? [y/N]: y
> [1/1] Upgrading indexinfo from 0.2.5 to 0.2.6...
> [1/1] Extracting indexinfo-0.2.6:   0%/usr/local/lib/libpkg.so.3: **Undefined symbol "utimensat"**
>

**Comment by bapt** [comment]
1 this has nothing to do with indexinfo as pkg is complaining, second that means you are using packages built on FreeBSD 10.3 on a box which is probably 10.1 or 10.2 (which are not supported anymore (since January 1rst)). You need to upgrade to a supported version of freebsd or stop using freebsd packages mirror and build your own.

**Comment by rknetwork** [comment]
> root@dev:/home/timeiwork/master/content/custom-styles # uname -a
> FreeBSD dev.xmpsoft.net 10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264: Fri Mar 25                                                                                                                                                              02:10:02 UTC 2016     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC                                                                                                                                                               amd64

**Comment by scorpio1441** [comment]
Could you provide a reference to the following statement?

> using packages ..... 10.1 or 10.2 (which are not supported anymore (since January 1rst)

**Comment by bapt** [comment]
freebsd builds official packages on the lowest supported version of a given branch meaning 10.1 until January 1rst, on January 1rst support was dropped for 10.1 and 10.2 meaning the packages are now built on 10.3 (which includes new symbols like openat, utimensat etc.)
see https://github.com/freebsd/pkg/issues/1526

To check what versions of freebsd are supported: https://www.freebsd.org/security/

And the announcements: https://lists.freebsd.org/pipermail/freebsd-announce/2016-October/001754.html
https://lists.freebsd.org/pipermail/freebsd-announce/2017-January/001779.html

**Comment by scorpio1441** [comment]
Thanks

**Comment by glaszig** [comment]
i just solved this without upgrading the entire OS by just using the proper FreeBSD repo url.

```
# freebsd-version
10.2-RELEASE-p10
# cat /usr/local/etc/pkg/repos/FreeBSD.conf
FreeBSD: {
  url: "pkg+http://pkg.FreeBSD.org/${ABI}/release_2",
  enabled: yes
}
```

http://glasz.org/sheeplog/2017/02/freebsd-usrlocalliblibpkgso3-undefined-symbol-utimensat.html
